memory load #0x8000 "out/test.bin"
run init until #0x7FFF = 0x01
registers show
memory show #0x5000 1
memory show #0x6000 1
run until #0x7FFF = 0x01
registers show
memory show #0x5000 1
memory show #0x6000 1
run until #0x7FFF = 0x01
registers show
memory show #0x5000 1
memory show #0x6000 1
run until #0x7FFF = 0x01
registers show
memory show #0x5000 1
memory show #0x6000 1
run until #0x7FFF = 0x01
registers show
memory show #0x5000 1
memory show #0x6000 1
run until #0x7FFF = 0x01
registers show
memory show #0x5000 2
memory show #0x6000 2
run until #0x7FFF = 0x01
registers show
memory show #0x5000 16
memory show #0x6000 16
run until #0x7FFF = 0x01
